CREATE TABLE IF NOT EXISTS departments (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL UNIQUE,parent_id INT NULL,leader_member_id INT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS members (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,stuno VARCHAR(40) NOT NULL UNIQUE,department_id INT NULL,bm VARCHAR(120) NULL,posts VARCHAR(120) NULL,grade VARCHAR(40) NULL,phone VARCHAR(60) NULL,email VARCHAR(120) NULL,status ENUM('active','trial','suspended','retired','left','graduated','disabled') NOT NULL DEFAULT 'active',tags VARCHAR(255) NULL,remark TEXT NULL,joined_at DATE NULL,left_at DATE NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_members_department (department_id),INDEX idx_members_status (status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS roles (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL UNIQUE,label VARCHAR(120) NOT NULL,permissions TEXT NULL,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS member_roles (member_id INT NOT NULL,role_id INT NOT NULL,PRIMARY KEY (member_id, role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS approvals (id INT AUTO_INCREMENT PRIMARY KEY,type VARCHAR(80) NOT NULL,title VARCHAR(180) NOT NULL,applicant_stuno VARCHAR(40) NULL,payload TEXT NULL,status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',reviewer VARCHAR(120) NULL,review_note TEXT NULL,created_at DATETIME NOT NULL,reviewed_at DATETIME NULL,INDEX idx_approvals_status (status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notifications (id INT AUTO_INCREMENT PRIMARY KEY,recipient_stuno VARCHAR(40) NULL,title VARCHAR(180) NOT NULL,content TEXT NOT NULL,read_at DATETIME NULL,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY,actor VARCHAR(120) NULL,action VARCHAR(120) NOT NULL,target_type VARCHAR(80) NULL,target_id VARCHAR(80) NULL,detail TEXT NULL,ip VARCHAR(64) NULL,created_at DATETIME NOT NULL,INDEX idx_audit_time (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS import_tasks (id INT AUTO_INCREMENT PRIMARY KEY,filename VARCHAR(255) NOT NULL,status ENUM('preview','confirmed','failed') NOT NULL DEFAULT 'preview',total_rows INT NOT NULL DEFAULT 0,valid_rows INT NOT NULL DEFAULT 0,invalid_rows INT NOT NULL DEFAULT 0,created_by VARCHAR(120) NULL,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS import_task_rows (id INT AUTO_INCREMENT PRIMARY KEY,task_id INT NOT NULL,row_no INT NOT NULL,name VARCHAR(120) NULL,stuno VARCHAR(40) NULL,bm VARCHAR(120) NULL,posts VARCHAR(120) NULL,is_valid TINYINT(1) NOT NULL DEFAULT 0,error_message TEXT NULL,INDEX idx_import_rows_task (task_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS member_status_histories (id INT AUTO_INCREMENT PRIMARY KEY,member_id INT NOT NULL,old_status VARCHAR(40) NULL,new_status VARCHAR(40) NOT NULL,reason TEXT NULL,actor VARCHAR(120) NULL,created_at DATETIME NOT NULL,INDEX idx_status_member (member_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Workflow, KPI and member capability modules
CREATE TABLE IF NOT EXISTS workflow_templates (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,category VARCHAR(80) NOT NULL DEFAULT 'general',description TEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_by VARCHAR(120) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS workflow_template_steps (id INT AUTO_INCREMENT PRIMARY KEY,template_id INT NOT NULL,step_order INT NOT NULL,step_name VARCHAR(120) NOT NULL,role_key VARCHAR(80) NULL,permission_key VARCHAR(120) NULL,sla_hours INT NOT NULL DEFAULT 72,created_at DATETIME NOT NULL,INDEX idx_wts_template (template_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS workflow_instances (id INT AUTO_INCREMENT PRIMARY KEY,template_id INT NULL,title VARCHAR(180) NOT NULL,object_type VARCHAR(80) NULL,object_id VARCHAR(80) NULL,applicant_stuno VARCHAR(40) NULL,current_step INT NOT NULL DEFAULT 1,status ENUM('draft','running','approved','rejected','cancelled') NOT NULL DEFAULT 'running',payload TEXT NULL,created_by VARCHAR(120) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_wi_status (status),INDEX idx_wi_object (object_type,object_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS workflow_tasks (id INT AUTO_INCREMENT PRIMARY KEY,instance_id INT NOT NULL,step_order INT NOT NULL,step_name VARCHAR(120) NOT NULL,assignee_role VARCHAR(80) NULL,assignee_stuno VARCHAR(40) NULL,status ENUM('pending','approved','rejected','skipped') NOT NULL DEFAULT 'pending',decision_note TEXT NULL,due_at DATETIME NULL,finished_by VARCHAR(120) NULL,finished_at DATETIME NULL,created_at DATETIME NOT NULL,INDEX idx_wt_instance (instance_id),INDEX idx_wt_status (status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS kpi_cycles (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,status ENUM('draft','active','closed') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS kpi_metrics (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,metric_key VARCHAR(80) NOT NULL UNIQUE,dimension VARCHAR(80) NOT NULL,weight DECIMAL(5,2) NOT NULL DEFAULT 1.00,max_score DECIMAL(8,2) NOT NULL DEFAULT 100.00,description TEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS kpi_records (id INT AUTO_INCREMENT PRIMARY KEY,cycle_id INT NOT NULL,member_id INT NOT NULL,metric_id INT NOT NULL,raw_value DECIMAL(10,2) NOT NULL DEFAULT 0,score DECIMAL(10,2) NOT NULL DEFAULT 0,evaluator VARCHAR(120) NULL,evidence TEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uniq_kpi (cycle_id,member_id,metric_id),INDEX idx_kpi_member (member_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS member_capabilities (id INT AUTO_INCREMENT PRIMARY KEY,member_id INT NOT NULL,dimension VARCHAR(80) NOT NULL,score DECIMAL(10,2) NOT NULL DEFAULT 0,level_label VARCHAR(80) NULL,evidence TEXT NULL,updated_by VARCHAR(120) NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uniq_capability (member_id,dimension)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
