<?php
$started=microtime(true);require_once __DIR__.'/../lib/bootstrap.php';$auth=auth_client();$user=null;$status=200;register_shutdown_function(function() use (&$auth,&$user,$started){if($user){$code=http_response_code();if(!$code||$code<100)$code=200;$auth->recordApiRequest($_SERVER,$code,(int)((microtime(true)-$started)*1000),$user);}});
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);$prefix='/DepartmentIFO/member-platform/api';$route=substr($path,strlen($prefix));if($route===''||$route===false)$route='/';$input=body();
function cn($u){return json_decode('"'.$u.'"');}
function row_count($sql,$params=[]){$s=db()->prepare($sql);$s->execute($params);$r=$s->fetch();return (int)($r['c']??0);} 
function eval_level($score){if($score>=90)return cn('\\u4f18\\u79c0');if($score>=80)return cn('\\u826f\\u597d');if($score>=70)return cn('\\u5408\\u683c');return cn('\\u5f85\\u63d0\\u5347');}
try{
 if($route==='/login'&&$_SERVER['REQUEST_METHOD']==='POST'){$res=$auth->login($input['username']??$input['stuno']??'',$input['password']??'');json_out($res,empty($res['ok'])?401:200);} 
 $user=$auth->requireAuth();
 if($route==='/dashboard/overview'){
  $total=row_count('SELECT COUNT(*) c FROM members');$active=row_count("SELECT COUNT(*) c FROM members WHERE status='active'");$disabled=row_count("SELECT COUNT(*) c FROM members WHERE status='disabled'");$pending=row_count("SELECT COUNT(*) c FROM approvals WHERE status='pending'");$avg=db()->query('SELECT COALESCE(AVG(total_score),0) c FROM evaluations')->fetch()['c'];
  $dept=db()->query('SELECT COALESCE(bm,"N/A") name,COUNT(*) c FROM members GROUP BY bm ORDER BY c DESC')->fetchAll();
  $recent=db()->query('SELECT action,actor,created_at FROM audit_logs ORDER BY id DESC LIMIT 8')->fetchAll();
  json_out(['ok'=>true,'total'=>$total,'active'=>$active,'disabled'=>$disabled,'pending_approvals'=>$pending,'avg_score'=>round((float)$avg,1),'departments'=>$dept,'recent'=>$recent]);
 }
 if($route==='/members'&&$_SERVER['REQUEST_METHOD']==='GET'){$q=$_GET['q']??'';$statusFilter=$_GET['status']??'';$dept=$_GET['department']??'';$params=[];$where=[];if($q!==''){$where[]='(m.name LIKE ? OR m.stuno LIKE ? OR m.bm LIKE ? OR m.posts LIKE ?)';array_push($params,"%$q%","%$q%","%$q%","%$q%");}if($statusFilter!==''){$where[]='m.status=?';$params[]=$statusFilter;}if($dept!==''){$where[]='m.bm=?';$params[]=$dept;}$sql='SELECT m.*,d.name department_name FROM members m LEFT JOIN departments d ON m.department_id=d.id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY m.id DESC LIMIT 800';$s=db()->prepare($sql);$s->execute($params);json_out(['ok'=>true,'data'=>$s->fetchAll()]);}
 if($route==='/members'&&$_SERVER['REQUEST_METHOD']==='POST'){$s=db()->prepare('INSERT INTO members(name,stuno,bm,posts,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');$s->execute([$input['name'],$input['stuno'],$input['bm']??'',$input['posts']??'','active',now(),now()]);audit($user['username'],'member.create','member',db()->lastInsertId(),json_encode($input,JSON_UNESCAPED_UNICODE));json_out(['ok'=>true,'id'=>db()->lastInsertId(),'message'=>cn('\\u6dfb\\u52a0\\u6210\\u529f')]);}
 if(preg_match('#^/members/(\d+)/(disable|restore|reset-password)$#',$route,$m)&&$_SERVER['REQUEST_METHOD']==='POST'){$id=(int)$m[1];$act=$m[2];if($act==='disable'){$old='active';$new='disabled';db()->prepare("UPDATE members SET status='disabled',updated_at=? WHERE id=?")->execute([now(),$id]);}elseif($act==='restore'){$old='disabled';$new='active';db()->prepare("UPDATE members SET status='active',updated_at=? WHERE id=?")->execute([now(),$id]);}else{$old='';$new='';}if($new){db()->prepare('INSERT INTO member_status_histories(member_id,old_status,new_status,reason,actor,created_at) VALUES(?,?,?,?,?,?)')->execute([$id,$old,$new,$input['reason']??'', $user['username'],now()]);}audit($user['username'],'member.'.$act,'member',$id,null);json_out(['ok'=>true,'message'=>cn('\\u64cd\\u4f5c\\u6210\\u529f')]);}
 if($route==='/organization/summary'){$departments=db()->query('SELECT d.id,d.name,d.parent_id,COUNT(m.id) member_count,SUM(m.status="active") active_count FROM departments d LEFT JOIN members m ON m.department_id=d.id GROUP BY d.id,d.name,d.parent_id ORDER BY d.id')->fetchAll();$posts=db()->query('SELECT COALESCE(posts,"N/A") name,COUNT(*) c FROM members GROUP BY posts ORDER BY c DESC LIMIT 20')->fetchAll();json_out(['ok'=>true,'departments'=>$departments,'posts'=>$posts]);}
 if($route==='/departments'){if($_SERVER['REQUEST_METHOD']==='GET')json_out(['ok'=>true,'data'=>db()->query('SELECT d.*,COUNT(m.id) member_count FROM departments d LEFT JOIN members m ON m.department_id=d.id GROUP BY d.id ORDER BY d.id')->fetchAll()]);if($_SERVER['REQUEST_METHOD']==='POST'){db()->prepare('INSERT INTO departments(name,parent_id,created_at,updated_at) VALUES(?,?,?,?)')->execute([$input['name'],$input['parent_id']??null,now(),now()]);audit($user['username'],'department.create','department',db()->lastInsertId(),$input['name']);json_out(['ok'=>true,'message'=>cn('\\u90e8\\u95e8\\u5df2\\u521b\\u5efa')]);}}
 if($route==='/evaluations'&&$_SERVER['REQUEST_METHOD']==='GET'){$sql='SELECT e.*,m.name member_name,m.stuno,m.bm,m.posts,c.name cycle_name FROM evaluations e JOIN members m ON e.member_id=m.id LEFT JOIN evaluation_cycles c ON e.cycle_id=c.id ORDER BY e.id DESC LIMIT 300';json_out(['ok'=>true,'data'=>db()->query($sql)->fetchAll(),'cycles'=>db()->query('SELECT * FROM evaluation_cycles ORDER BY id DESC')->fetchAll()]);}
 if($route==='/evaluations'&&$_SERVER['REQUEST_METHOD']==='POST'){$scores=[(int)($input['work_score']??0),(int)($input['discipline_score']??0),(int)($input['collaboration_score']??0),(int)($input['growth_score']??0)];$total=array_sum($scores);$level=eval_level($total);$cycle=$input['cycle_id']??row_count('SELECT MAX(id) c FROM evaluation_cycles');db()->prepare('INSERT INTO evaluations(cycle_id,member_id,evaluator,work_score,discipline_score,collaboration_score,growth_score,total_score,level,comment,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$cycle,$input['member_id'],$user['username'],$scores[0],$scores[1],$scores[2],$scores[3],$total,$level,$input['comment']??'',now(),now()]);audit($user['username'],'evaluation.create','member',$input['member_id'],'score='.$total);json_out(['ok'=>true,'message'=>cn('\\u8003\\u6838\\u8bb0\\u5f55\\u5df2\\u4fdd\\u5b58'),'total_score'=>$total,'level'=>$level]);}
 if($route==='/evaluations/summary'){$summary=db()->query('SELECT COALESCE(m.bm,"N/A") department,COUNT(e.id) evaluated,ROUND(AVG(e.total_score),1) avg_score FROM members m LEFT JOIN evaluations e ON e.member_id=m.id GROUP BY m.bm ORDER BY avg_score DESC')->fetchAll();json_out(['ok'=>true,'data'=>$summary]);}
 if($route==='/approvals'){if($_SERVER['REQUEST_METHOD']==='GET')json_out(['ok'=>true,'data'=>db()->query('SELECT * FROM approvals ORDER BY id DESC LIMIT 200')->fetchAll()]);if($_SERVER['REQUEST_METHOD']==='POST'){db()->prepare('INSERT INTO approvals(type,title,applicant_stuno,payload,status,created_at) VALUES(?,?,?,?,?,?)')->execute([$input['type']??'generic',$input['title'],$user['username'],json_encode($input['payload']??[],JSON_UNESCAPED_UNICODE),'pending',now()]);audit($user['username'],'approval.create','approval',db()->lastInsertId(),$input['title']);json_out(['ok'=>true,'message'=>cn('\\u7533\\u8bf7\\u5df2\\u63d0\\u4ea4')]);}}
 if(preg_match('#^/approvals/(\d+)/(approve|reject)$#',$route,$m)&&$_SERVER['REQUEST_METHOD']==='POST'){db()->prepare('UPDATE approvals SET status=?,reviewer=?,review_note=?,reviewed_at=? WHERE id=?')->execute([$m[2]==='approve'?'approved':'rejected',$user['username'],$input['note']??'',now(),(int)$m[1]]);audit($user['username'],'approval.'.$m[2],'approval',$m[1],$input['note']??'');json_out(['ok'=>true,'message'=>cn('\\u5ba1\\u6279\\u5df2\\u5904\\u7406')]);}
 if($route==='/audit-logs')json_out(['ok'=>true,'data'=>db()->query('SELECT * FROM audit_logs ORDER BY id DESC LIMIT 300')->fetchAll()]);
 if($route==='/imports/preview'&&$_SERVER['REQUEST_METHOD']==='POST'){if(empty($_FILES['file']))json_out(['ok'=>false,'message'=>cn('\\u6ca1\\u6709\\u4e0a\\u4f20\\u6587\\u4ef6')],400);$file=$_FILES['file'];$name=$file['name'];$dest=__DIR__.'/../uploads/imports/'.time().'_'.preg_replace('/[^A-Za-z0-9_.-]/','_',$name);move_uploaded_file($file['tmp_name'],$dest);$rows=parse_member_import_file($dest);$taskRows=[];$valid=0;for($i=1;$i<count($rows);$i++){$r=$rows[$i];$err=[];$st=trim($r[1]??'');$nm=trim($r[0]??'');if($nm==='')$err[]=cn('\\u59d3\\u540d\\u4e3a\\u7a7a');if($st==='')$err[]=cn('\\u5b66\\u53f7\\u4e3a\\u7a7a');$du=db()->prepare('SELECT id FROM members WHERE stuno=?');$du->execute([$st]);if($st&&$du->fetch())$err[]=cn('\\u5b66\\u53f7\\u5df2\\u5b58\\u5728');if(!$err)$valid++;$taskRows[]=['row_no'=>$i+1,'name'=>$nm,'stuno'=>$st,'bm'=>trim($r[2]??''),'posts'=>trim($r[3]??''),'is_valid'=>!$err,'error'=>implode(';',$err)];}db()->prepare('INSERT INTO import_tasks(filename,status,total_rows,valid_rows,invalid_rows,created_by,created_at) VALUES(?,?,?,?,?,?,?)')->execute([$name,'preview',count($taskRows),$valid,count($taskRows)-$valid,$user['username'],now()]);$tid=db()->lastInsertId();$ins=db()->prepare('INSERT INTO import_task_rows(task_id,row_no,name,stuno,bm,posts,is_valid,error_message) VALUES(?,?,?,?,?,?,?,?)');foreach($taskRows as $r)$ins->execute([$tid,$r['row_no'],$r['name'],$r['stuno'],$r['bm'],$r['posts'],$r['is_valid']?1:0,$r['error']]);audit($user['username'],'import.preview','import_task',$tid,$name);json_out(['ok'=>true,'task_id'=>$tid,'rows'=>$taskRows]);}
 if(preg_match('#^/imports/(\d+)/confirm$#',$route,$m)&&$_SERVER['REQUEST_METHOD']==='POST'){$tid=(int)$m[1];$rows=db()->query('SELECT * FROM import_task_rows WHERE task_id='.$tid.' AND is_valid=1')->fetchAll();$ins=db()->prepare('INSERT IGNORE INTO members(name,stuno,bm,posts,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');foreach($rows as $r)$ins->execute([$r['name'],$r['stuno'],$r['bm'],$r['posts'],'active',now(),now()]);db()->prepare("UPDATE import_tasks SET status='confirmed' WHERE id=?")->execute([$tid]);audit($user['username'],'import.confirm','import_task',$tid,count($rows).' rows');json_out(['ok'=>true,'inserted'=>count($rows),'message'=>cn('\\u5bfc\\u5165\\u5df2\\u786e\\u8ba4')]);}
 if($route==='/export/members'){header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="members.csv"');$out=fopen('php://output','w');fputcsv($out,[cn('\\u59d3\\u540d'),cn('\\u5b66\\u53f7'),cn('\\u90e8\\u95e8'),cn('\\u804c\\u52a1'),cn('\\u72b6\\u6001')]);foreach(db()->query('SELECT name,stuno,bm,posts,status FROM members ORDER BY id') as $r)fputcsv($out,$r);exit;}
 json_out(['ok'=>false,'message'=>cn('\\u63a5\\u53e3\\u4e0d\\u5b58\\u5728'),'route'=>$route],404);
}catch(Throwable $e){$status=500;$auth->reportException($e,$user);json_out(['ok'=>false,'message'=>cn('\\u670d\\u52a1\\u5668\\u9519\\u8bef'),'error'=>$e->getMessage()],500);}finally{if($user)$auth->recordApiRequest($_SERVER,$status,(int)((microtime(true)-$started)*1000),$user);}
